[package]
name = "metronome-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.17"
crossterm = "0.19"
include_dir = "0.7.3" # Check for the latest version on crates.io

